### ISSUE TITLE
robottle_python_packages missed

### ISSUE THREAD

**Issue by SiChiTong** [arthurBricq/ros_robottle#1]
Sir I would like to introduce the package to my colleagues but it missed the utils from the robottle_python_packages. Can you share the packages again?

**Comment by arthurBricq** [comment]
Hello, 
I am glad to hear you're trying to make it work ! I think it might be difficult to make it work 100% without the same hardware setup, but good to know it can be reused.

I haven't touched the code since a long time and have changed computer since then, but i will give a look in my old computer tonight (European time) for this missing file and let you know. Let me know if I give you more help :+1:

**Comment by SiChiTong** [comment]
It really helps a lot and thanks for your quick response sir

**Comment by arthurBricq** [comment]
Hello. I have not found a missing file name 'utils', could you maybe show me the steps you are trying to reproduce and the associated error ?

**Comment by SiChiTong** [comment]
> Hello. I have not found a missing file name 'utils', could you maybe show me the steps you are trying to reproduce and the associated error ?

https://github.com/arthurBricq/ros_robottle/blob/main/src/robottle/robottle/controller1.py#L11
 it uses the robottle_utils package everywhere
but I can't find the package anywhere from the repo

**Comment by arthurBricq** [comment]
Oh ok that is your problem.  As mentionned in the Readme.md there's an additional python package that we had created to work with our code : https://github.com/arthurBricq/robottle_python_packages. There should be installation instruction, you have to install the package locally with pip using a command like `pip install .` (eventually with sudo rights)

**Comment by SiChiTong** [comment]
https://github.com/arthurBricq/robottle_python_packages
Is it actually existing?

**Comment by SiChiTong** [comment]
![Screenshot_2022-06-22-16-06-14-649_com android chrome](https://user-images.githubusercontent.com/8967368/174977518-f0e6c1d3-8091-4418-b9c8-b7c06b206d9a.jpg)

**Comment by arthurBricq** [comment]
How about now ? Sorry i had let it private !

**Comment by SiChiTong** [comment]
Yes we finally come with it 
Many thanks for your sharing
